# Generated by Django 5.2.3 on 2025-07-20 08:24

import ckeditor_uploader.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='product name')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='slug')),
                ('product_code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='product code')),
                ('size_or_weight', models.CharField(help_text='e.g., 500g, 1L, Large, etc.', max_length=100, verbose_name='size or weight')),
                ('image', models.ImageField(upload_to='products/', verbose_name='product image')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='products in stock')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['-date_added'],
            },
        ),
    ]
