# Generated by Django 5.2.3 on 2025-07-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0002_remove_orderitem_image_remove_orderitem_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
