# Generated by Django 5.2.3 on 2025-07-21 15:06

import e_commerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=e_commerce.models.generate_order_id, editable=False, max_length=100, unique=True),
        ),
    ]
